# Generated by Django 3.2 on 2022-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.PositiveBigIntegerField(unique=True)),
                ('chat_id', models.PositiveBigIntegerField(unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('lang', models.CharField(blank=True, choices=[('uz', 'uz'), ('ru', 'ru')], max_length=3, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('send_message_type', models.CharField(blank=True, choices=[('phone', 'phone'), ('telegram', 'telegram'), ('both', 'both')], max_length=25, null=True)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
