# Generated by Django 3.2 on 2022-10-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
