# Generated by Django 3.2 on 2022-10-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
